Oops! Assertion failed

The following assertion was not satisfied
  assert foo(*[1,2]) is False, error()

Assertion values
  assert foo(*[1,2]) is False, error()
              ^ is = [1, 2]
  assert foo(*[1,2]) is False, error()
         ^ is = (1, 2)
  assert foo(*[1,2]) is False, error()
                     ^ is = False
  assert foo(*[1,2]) is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 95 in 'run'

87|              
88|                  with subsuite.test("*args") as test:
89|                      vs = []
90|                      def foo(*x):
91|                          test.note(x)
92|                          vs.append(x)
93|                          return x
94|                      with raises(AssertionError) as e:
95|>                         assert foo(*[1,2]) is False, error()
96|                      test.note(e.exception)
97|                      with test.test("assert *args are the same"):
98|                          assert vs[0] == vs[1]
