Oops! Assertion failed

The following assertion was not satisfied
  assert (lambda x: x+1)(1) is False, error()

Assertion values
  assert (lambda x: x+1)(1) is False, error()
          ^ is = 2
  assert (lambda x: x+1)(1) is False, error()
                            ^ is = False
  assert (lambda x: x+1)(1) is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 456 in 'run'

448|                      with raises(AssertionError) as e:
449|                          assert (lambda x: x)(1) is False, error()
450|                      test.note(e.exception)
451|                      with this() as that:
452|                          assert that(snapshot(e.exception, "common-idioms-lambda-name", encoder=str)), error()
453|  
454|                  with subsuite.test("lambda expr") as test:
455|                      with raises(AssertionError) as e:
456|>                         assert (lambda x: x+1)(1) is False, error()
457|                      test.note(e.exception)
458|                      with this() as that:
459|                          assert that(snapshot(e.exception, "common-idioms-lambda-expr", encoder=str)), error()
